version: '3.3'
services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: swag_reverse
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 10080:80
  load_balancer_1:
    image: nginx
    environment:
      VIRTUAL_HOST: hello-there.htm
  load_balancer_2:
    image: nginx
    environment:
      VIRTUAL_HOST: hello-there.htm
  load_balancer_3:
    image: nginx
    environment:
      VIRTUAL_HOST: hello-there.htm
  load_balancer_4:
    image: nginx
    environment:
      VIRTUAL_HOST: hello-there.htm
